//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsumirServicioWCF.ServiceMedicamento {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="MedicamentoCLS", Namespace="http://schemas.datacontract.org/2004/07/ServiciosMedicamentos.Clases")]
    [System.SerializableAttribute()]
    public partial class MedicamentoCLS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iidmedicamentoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string concentracionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iidformafarmaceuticaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreFormaFarmaceuticaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal precioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int stockField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string presentacionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iidmedicamento {
            get {
                return this.iidmedicamentoField;
            }
            set {
                if ((this.iidmedicamentoField.Equals(value) != true)) {
                    this.iidmedicamentoField = value;
                    this.RaisePropertyChanged("iidmedicamento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombre {
            get {
                return this.nombreField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreField, value) != true)) {
                    this.nombreField = value;
                    this.RaisePropertyChanged("nombre");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string concentracion {
            get {
                return this.concentracionField;
            }
            set {
                if ((object.ReferenceEquals(this.concentracionField, value) != true)) {
                    this.concentracionField = value;
                    this.RaisePropertyChanged("concentracion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int iidformafarmaceutica {
            get {
                return this.iidformafarmaceuticaField;
            }
            set {
                if ((this.iidformafarmaceuticaField.Equals(value) != true)) {
                    this.iidformafarmaceuticaField = value;
                    this.RaisePropertyChanged("iidformafarmaceutica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string nombreFormaFarmaceutica {
            get {
                return this.nombreFormaFarmaceuticaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreFormaFarmaceuticaField, value) != true)) {
                    this.nombreFormaFarmaceuticaField = value;
                    this.RaisePropertyChanged("nombreFormaFarmaceutica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public decimal precio {
            get {
                return this.precioField;
            }
            set {
                if ((this.precioField.Equals(value) != true)) {
                    this.precioField = value;
                    this.RaisePropertyChanged("precio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int stock {
            get {
                return this.stockField;
            }
            set {
                if ((this.stockField.Equals(value) != true)) {
                    this.stockField = value;
                    this.RaisePropertyChanged("stock");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string presentacion {
            get {
                return this.presentacionField;
            }
            set {
                if ((object.ReferenceEquals(this.presentacionField, value) != true)) {
                    this.presentacionField = value;
                    this.RaisePropertyChanged("presentacion");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FormaFarmaceuticaCLS", Namespace="http://schemas.datacontract.org/2004/07/ServiciosMedicamentos.Clases")]
    [System.SerializableAttribute()]
    public partial class FormaFarmaceuticaCLS : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int iidformafarmaceuticaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string nombreFormaFarmaceuticaField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int iidformafarmaceutica {
            get {
                return this.iidformafarmaceuticaField;
            }
            set {
                if ((this.iidformafarmaceuticaField.Equals(value) != true)) {
                    this.iidformafarmaceuticaField = value;
                    this.RaisePropertyChanged("iidformafarmaceutica");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nombreFormaFarmaceutica {
            get {
                return this.nombreFormaFarmaceuticaField;
            }
            set {
                if ((object.ReferenceEquals(this.nombreFormaFarmaceuticaField, value) != true)) {
                    this.nombreFormaFarmaceuticaField = value;
                    this.RaisePropertyChanged("nombreFormaFarmaceutica");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceMedicamento.IMedicamentos")]
    public interface IMedicamentos {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/listarMedicamentos", ReplyAction="http://tempuri.org/IMedicamentos/listarMedicamentosResponse")]
        System.Collections.Generic.List<ConsumirServicioWCF.ServiceMedicamento.MedicamentoCLS> listarMedicamentos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/listarMedicamentos", ReplyAction="http://tempuri.org/IMedicamentos/listarMedicamentosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServicioWCF.ServiceMedicamento.MedicamentoCLS>> listarMedicamentosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/listarFormaFarmaceutica", ReplyAction="http://tempuri.org/IMedicamentos/listarFormaFarmaceuticaResponse")]
        System.Collections.Generic.List<ConsumirServicioWCF.ServiceMedicamento.FormaFarmaceuticaCLS> listarFormaFarmaceutica();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/listarFormaFarmaceutica", ReplyAction="http://tempuri.org/IMedicamentos/listarFormaFarmaceuticaResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServicioWCF.ServiceMedicamento.FormaFarmaceuticaCLS>> listarFormaFarmaceuticaAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/recuperarMedicamento", ReplyAction="http://tempuri.org/IMedicamentos/recuperarMedicamentoResponse")]
        ConsumirServicioWCF.ServiceMedicamento.MedicamentoCLS recuperarMedicamento(int iidMedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/recuperarMedicamento", ReplyAction="http://tempuri.org/IMedicamentos/recuperarMedicamentoResponse")]
        System.Threading.Tasks.Task<ConsumirServicioWCF.ServiceMedicamento.MedicamentoCLS> recuperarMedicamentoAsync(int iidMedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/registrarYactualizarMedicamento", ReplyAction="http://tempuri.org/IMedicamentos/registrarYactualizarMedicamentoResponse")]
        int registrarYactualizarMedicamento(ConsumirServicioWCF.ServiceMedicamento.MedicamentoCLS oMedicamentoCLS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/registrarYactualizarMedicamento", ReplyAction="http://tempuri.org/IMedicamentos/registrarYactualizarMedicamentoResponse")]
        System.Threading.Tasks.Task<int> registrarYactualizarMedicamentoAsync(ConsumirServicioWCF.ServiceMedicamento.MedicamentoCLS oMedicamentoCLS);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/eliminarMedicamento", ReplyAction="http://tempuri.org/IMedicamentos/eliminarMedicamentoResponse")]
        int eliminarMedicamento(int iidMedicamento);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMedicamentos/eliminarMedicamento", ReplyAction="http://tempuri.org/IMedicamentos/eliminarMedicamentoResponse")]
        System.Threading.Tasks.Task<int> eliminarMedicamentoAsync(int iidMedicamento);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMedicamentosChannel : ConsumirServicioWCF.ServiceMedicamento.IMedicamentos, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MedicamentosClient : System.ServiceModel.ClientBase<ConsumirServicioWCF.ServiceMedicamento.IMedicamentos>, ConsumirServicioWCF.ServiceMedicamento.IMedicamentos {
        
        public MedicamentosClient() {
        }
        
        public MedicamentosClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MedicamentosClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedicamentosClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MedicamentosClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.List<ConsumirServicioWCF.ServiceMedicamento.MedicamentoCLS> listarMedicamentos() {
            return base.Channel.listarMedicamentos();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServicioWCF.ServiceMedicamento.MedicamentoCLS>> listarMedicamentosAsync() {
            return base.Channel.listarMedicamentosAsync();
        }
        
        public System.Collections.Generic.List<ConsumirServicioWCF.ServiceMedicamento.FormaFarmaceuticaCLS> listarFormaFarmaceutica() {
            return base.Channel.listarFormaFarmaceutica();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<ConsumirServicioWCF.ServiceMedicamento.FormaFarmaceuticaCLS>> listarFormaFarmaceuticaAsync() {
            return base.Channel.listarFormaFarmaceuticaAsync();
        }
        
        public ConsumirServicioWCF.ServiceMedicamento.MedicamentoCLS recuperarMedicamento(int iidMedicamento) {
            return base.Channel.recuperarMedicamento(iidMedicamento);
        }
        
        public System.Threading.Tasks.Task<ConsumirServicioWCF.ServiceMedicamento.MedicamentoCLS> recuperarMedicamentoAsync(int iidMedicamento) {
            return base.Channel.recuperarMedicamentoAsync(iidMedicamento);
        }
        
        public int registrarYactualizarMedicamento(ConsumirServicioWCF.ServiceMedicamento.MedicamentoCLS oMedicamentoCLS) {
            return base.Channel.registrarYactualizarMedicamento(oMedicamentoCLS);
        }
        
        public System.Threading.Tasks.Task<int> registrarYactualizarMedicamentoAsync(ConsumirServicioWCF.ServiceMedicamento.MedicamentoCLS oMedicamentoCLS) {
            return base.Channel.registrarYactualizarMedicamentoAsync(oMedicamentoCLS);
        }
        
        public int eliminarMedicamento(int iidMedicamento) {
            return base.Channel.eliminarMedicamento(iidMedicamento);
        }
        
        public System.Threading.Tasks.Task<int> eliminarMedicamentoAsync(int iidMedicamento) {
            return base.Channel.eliminarMedicamentoAsync(iidMedicamento);
        }
    }
}
